#!/bin/bash

echo "🚀 Quick GitHub Push Helper"
echo "=========================="
echo ""
echo "Since git push is having auth issues, let's use the web interface:"
echo ""
echo "1. Go to: https://github.com/AntreasCh/jarvis-cv"
echo "2. Click 'Add file' → 'Upload files'"
echo "3. Upload these files:"
echo "   - web_app_railway.py"
echo "   - Procfile" 
echo "   - start_railway.py"
echo "   - railway_requirements.txt"
echo ""
echo "4. Commit message: 'Fix Railway deployment - remove audio dependencies'"
echo "5. Click 'Commit changes'"
echo ""
echo "This will trigger Railway to redeploy automatically!"
echo ""
echo "Alternative: Try this command with your GitHub token:"
echo "git push https://YOUR_TOKEN@github.com/AntreasCh/jarvis-cv.git main"
